#!/bin/bash
#
#
# curl https://olivierodo.me/dev | bash -
#
#

CURRENT_USER=$(whoami)

echo $CURRENT_USER

## Packages
sudo apt-get update
sudo apt-get install -y \
  apt-transport-https \
  ca-certificates \
  curl \
  gnupg2 \
  software-properties-common \
  jq \
  git \
  tmux

## Install Docker
curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -

sudo apt-key fingerprint 0EBFCD88

sudo add-apt-repository \
  "deb [arch=amd64] https://download.docker.com/linux/debian \
  $(lsb_release -cs) \
  stable"

sudo apt-get update

sudo apt-get install -y \
  docker-ce docker-ce-cli \
  containerd.io

sudo usermod -aG docker $CURRENT_USER

sudo su -s /bin/bash -c 'docker version' $CURRENT_USER

## Kubectl

curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
chmod +x ./kubectl
sudo mv ./kubectl /usr/local/bin/kubectl
kubectl version

## Custom config

git clone https://github.com/olivierodo/dotfiles.git

sudo su -s /bin/bash -c 'cd ./dotfiles && exec ./install.sh' $CURRENT_USER

echo "==================================================================="
echo "SUCCESSFULL INSTALLATION !!!"
echo "==================================================================="
echo "==================================================================="
echo "==================================================================="
echo "Please exit and log yourself again"
echo "==================================================================="
