#!/bin/bash
#
#
# sudo curl https://olivierodo.me/mac | bash -
#
#

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew doctor

# install softwares

brew install --force \
  git \
  tmux \
  jq \
  task \
  kubernetes-cli \
  there \
  gh

# M3 Warning
# google-cloud-sdk:  https://dontreinventbicycle.com/m1-gcloud-early-2021.html
brew install --cask \
  alfred \
  spotify \
  opera \
  insomnia \
  docker \
  gitify \
  macpass \
  caffeine \
  mongodb-compass
  google-cloud-sdk \
  sequel-pro \
  balenaetcher \
  alacritty \
  vlc \
  shureplus-motiv \
  anki \ 
  logi-options-plus \
  nordvpn

## Define bash as shell
chsh -s /bin/bash

## Dev config
cd ~
CURRENT_USER=$(whoami)

git clone https://github.com/olivierodo/dotfiles.git

cd ./dotfiles
sh ./install.sh

