#!/bin/bash
#
#
# curl https://olivierodo.me/mac | bash -
#
#

ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew doctor

# install softwares

brew install git \
  tmux \
  jq

brew cask install \
  station \
  alfred \
  iterm2 \
  spotify \
  opera \
  insomnia \
  docker \
  google-backup-and-sync \
  keepassx \
  caffeine \
  mongodb-compass \
  google-cloud-sdk \
  sequel-pro \
  recordit \
  kubectl \
  balenaetcher \
  vlc

## Define bash as shell
chsh -s /bin/bash

## Add iterms to the login items
osascript -e 'tell application "System Events" to make login item at end with properties {path:"/Applications/iTerm.app", hidden:false}'




## Dev config
cd ~
CURRENT_USER=$(whoami)

git clone https://github.com/olivierodo/dotfiles.git

cd ./dotfiles
sh ./install.sh

