#!/bin/bash

CURRENT_USER=$(whoami)

echo $CURRENT_USER

sudo apt-get update
sudo apt-get install -y \
  apt-transport-https \
  ca-certificates \
  curl \
  gnupg2 \
  software-properties-common \
  git \
  tmux \

curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -

sudo apt-key fingerprint 0EBFCD88

sudo add-apt-repository \
  "deb [arch=amd64] https://download.docker.com/linux/debian \
  $(lsb_release -cs) \
  stable"

sudo apt-get update

sudo apt-get install -y \
  docker-ce docker-ce-cli \
  containerd.io

sudo usermod -aG docker $CURRENT_USER

#docker version

git clone https://github.com/olivierodo/dotfiles.git

sh ./dotfiles/install.sh
